"""
Download service — creates downloadable ZIP files of generated websites.
"""

import os
import zipfile
import uuid
from config.logging_config import get_logger

logger = get_logger(__name__)

DOWNLOADS_DIR = "downloads"


def create_website_zip(project_name: str, html: str, css: str, js: str) -> str:
    """
    Package generated website files into a ZIP archive.
    Returns the path to the created ZIP file.
    """
    os.makedirs(DOWNLOADS_DIR, exist_ok=True)

    # Sanitize project name for folder
    safe_name = "".join(c if c.isalnum() or c in "-_ " else "" for c in project_name).strip()
    safe_name = safe_name.replace(" ", "-").lower() or "website"

    zip_filename = f"{safe_name}-{uuid.uuid4().hex[:8]}.zip"
    zip_path = os.path.join(DOWNLOADS_DIR, zip_filename)

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        # Write HTML
        zf.writestr(f"{safe_name}/index.html", html or "")
        # Write CSS
        zf.writestr(f"{safe_name}/style.css", css or "")
        # Write JavaScript
        zf.writestr(f"{safe_name}/script.js", js or "")
        # Write a simple README
        readme = f"# {project_name}\n\nGenerated by SiteGen AI\n\nOpen index.html in your browser to view the website."
        zf.writestr(f"{safe_name}/README.md", readme)

    logger.info(f"ZIP created: {zip_path}")
    return zip_path
